"""Guard ``docs/reference/reference/cli.md`` against drifting from the real Typer surface.

Walks the live ``agent_guardian.cli`` Typer app and asserts that every command
name — and the first long flag of every option on the ``scan`` command — is
referenced somewhere in ``docs/reference/reference/cli.md``. New flags landing in code
without a corresponding doc update will fail this test in CI.

The CLI reference page moved from ``docs/reference/cli.md`` to ``docs/reference/reference/cli.md``
when the v1.0 docs IA was reorganised (concepts/tutorials/how-to/reference);
the ``docs/reference/cli.md`` URL is preserved via mkdocs redirects.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import typer
import typer.main

from agent_guardian.cli import app

REPO_ROOT = Path(__file__).resolve().parents[2]
DOC = REPO_ROOT / "docs" / "reference" / "cli.md"


def _commands_from_app(typer_app: typer.Typer, prefix: str = "") -> list[str]:
    """Walk a Typer app and return ``["scan", "doctor", "telemetry essential", ...]``."""

    out: list[str] = []
    info = typer.main.get_command(typer_app)
    # ``info`` is a Click group; its ``commands`` attribute holds the children.
    commands = getattr(info, "commands", {})
    for name, cmd in commands.items():
        full = f"{prefix}{name}".strip()
        out.append(full)
        if getattr(cmd, "commands", None):
            # Sub-app (e.g. ``telemetry``, ``contract``) — recurse one level.
            for sub_name in cmd.commands:
                out.append(f"{full} {sub_name}".strip())
    return out


def _scan_options() -> list[str]:
    """Long flags (--foo) declared on the ``scan`` command in cli.py."""

    info = typer.main.get_command(app)
    scan_cmd = info.commands["scan"]  # type: ignore[union-attr]
    flags: list[str] = []
    for param in scan_cmd.params:
        # Click ``Option`` objects expose ``opts`` — pick the first long form.
        long_flags = [opt for opt in getattr(param, "opts", ()) if opt.startswith("--")]
        if long_flags:
            flags.append(long_flags[0])
    return flags


@pytest.fixture(scope="module")
def doc_body() -> str:
    return DOC.read_text(encoding="utf-8")


# Commands we deliberately exclude — sub-command groupings whose individual
# children are intentionally elided from the user-facing docs (housekeeping or
# experimental tools that the reference page doesn't yet cover).
_SKIP_COMMAND_NAMES = frozenset(
    {
        # ``scans`` sub-app — local scan-store housekeeping (list / delete /
        # purge). Operator-facing, not red-team-facing; documented only via
        # ``--help`` until v1.1 stabilises the surface.
        "scans",
        "scans list",
        "scans delete",
        "scans purge",
        # ``telemetry essential`` / ``extended`` / ``reset`` / ``show`` —
        # documented as a group under the Telemetry transparency page; reference/cli.md
        # covers the user-facing ``enable`` / ``disable`` / ``status`` set.
        "telemetry essential",
        "telemetry extended",
        "telemetry reset",
        "telemetry show",
    }
)


@pytest.mark.parametrize("command", _commands_from_app(app))
def test_command_documented(command: str, doc_body: str) -> None:
    if command in _SKIP_COMMAND_NAMES:
        pytest.skip(f"{command!r} intentionally not documented in reference/cli.md")
    # We accept either a fenced code-block reference (``agent-guardian scan``)
    # or an H2 anchor (``## ``scan```). Both are common in reference/cli.md.
    needles = (
        f"agent-guardian {command}",
        f"`{command}`",
    )
    assert any(needle in doc_body for needle in needles), (
        f"docs/reference/cli.md does not reference the {command!r} command — add an H2 + "
        f"a code-block example before merging."
    )


# Boolean flags whose negated form is auto-generated by Typer (``--owasp-llm`` /
# ``--no-owasp-llm``) — we document the positive form only.
_DOC_SKIP_FLAGS = frozenset(
    {
        "--framework-ref",  # paired with --framework; covered by the contract path.
        "--no-preflight",  # the positive default is the documented behaviour.
        "--no-owasp-llm",  # ``--owasp-llm`` covers the toggle.
    }
)


@pytest.mark.parametrize("flag", _scan_options())
def test_scan_flag_documented(flag: str, doc_body: str) -> None:
    if flag in _DOC_SKIP_FLAGS:
        pytest.skip(f"{flag!r} intentionally omitted from docs")
    assert flag in doc_body, (
        f"docs/reference/cli.md does not mention the {flag!r} option on the scan command — "
        f"add it to the options table."
    )
